### ISSUE TITLE
Status inactive

### ISSUE THREAD

**Issue by Fazliddin7798** [rolling-scopes/rsschool-app#1201]
**Course**
RS LT (Planned) 2022

**What is wrong**
Status: inactive
![image](https://user-images.githubusercontent.com/92352504/153016062-5e74ee8a-2ab6-492d-9f77-f83eac162a27.png)

**Comment by PolinaYu** [comment]
I have the same problem.

**Comment by apalchys** [comment]
Could it be a case that you missed some deadlines?

**Comment by PolinaYu** [comment]
This iteration of RS school just started (on feb 1), first deadline will be
only on feb 12. But probably the problem is that I registered to the school
too late? I believe it was 4 days ago.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dzmitry-varabei** [comment]
@Fazliddin7798 fixed. Login again plz.
