### ISSUE TITLE
RS 2019 Q3: Ищу ментора

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#240]

**Comment by ALisetskii** [comment]
Добрый день, прошел собеседование 31 октября, после этого у ментора не было возможности проверять мои таски, и не будет возможности быть моим ментором. ищу нового ментора

**Comment by KotdenGit** [comment]
Добрый день. У меня не было собеседования где могли проверить мои знания английского языка, ментор ко мне не прикреплён.

**Comment by dzmitry-varabei** [comment]
@ALisetskii привет! залей плиз все таски, которые у тебя есть в приватный репозиторий 
https://github.com/rolling-scopes-school/alisetskii-RS2019Q3 и открой необходимые PR.
И потом отпишись сюда еще раз - назначу тебе ментора

**Comment by ALisetskii** [comment]
@dzmitry-varabei таски залил, PR открыл, отписываюсь сюда еще раз.

**Comment by KotdenGit** [comment]
Да спасибо большое, я займусь этим в ближайшее время.                                                                                                                                                                                                                                                                                                                                        Отправлено с моего смартфона BlackBerry 10.                                                                                                                                                                                                                От: ALisetskiiОтправлено: пятніца, 29 лістапад 2019 20.38Кому: rolling-scopes/rsschool-appОтветить: rolling-scopes/rsschool-appКопия: KotdenGit; CommentТема: Re: [rolling-scopes/rsschool-app] RS 2019 Q3: Ищу ментора (#240)@dzmitry-varabei таски залил, PR открыл, отписываюсь сюда еще раз.



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/rolling-scopes/rsschool-app/issues/240?email_source=notifications\u0026email_token=AEL7VJVW3RXEI5SFQIKM3STQWFHPTA5CNFSM4JQCKGQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFPKYYI#issuecomment-559852641",

"url": "https://github.com/rolling-scopes/rsschool-app/issues/240?email_source=notifications\u0026email_token=AEL7VJVW3RXEI5SFQIKM3STQWFHPTA5CNFSM4JQCKGQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFPKYYI#issuecomment-559852641",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by dzmitry-varabei** [comment]
@ALisetskii перевел тебя к ментору @leovvay.

**Comment by dzmitry-varabei** [comment]
@KotdenGit перевел тебя к ментору @mikalai-sokarau.

**Comment by leovvay** [comment]
@ALisetskii укажи, пожалуйста, как с тобой связаться в твоём профиле.

**Comment by KotdenGit** [comment]
Хорошо, минуту                                                                                                                                                                                                                                                                                                                                        Отправлено с моего смартфона BlackBerry 10.                                                                                                                                                                                                                От: leovvayОтправлено: субота, 30 лістапад 2019 13.19Кому: rolling-scopes/rsschool-appОтветить: rolling-scopes/rsschool-appКопия: KotdenGit; MentionТема: Re: [rolling-scopes/rsschool-app] RS 2019 Q3: Ищу ментора (#240)@ALisetskii укажи, пожалуйста, как с тобой связаться в твоём профиле.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/rolling-scopes/rsschool-app/issues/240?email_source=notifications\u0026email_token=AEL7VJTJRADDLXKXA3VCFODQWI43FA5CNFSM4JQCKGQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFQAT3I#issuecomment-559942125",

"url": "https://github.com/rolling-scopes/rsschool-app/issues/240?email_source=notifications\u0026email_token=AEL7VJTJRADDLXKXA3VCFODQWI43FA5CNFSM4JQCKGQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFQAT3I#issuecomment-559942125",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ALisetskii** [comment]
@dzmitry-varabei 
указал в профиле контактные данные
в .rs.school страница ментора мне недоступна, поэтому не могу сам написать.

**Comment by ALisetskii** [comment]
@leovvay 
указал в профиле rsschool свои контакты.
у меня в Stage Interview пока контакты старого ментора, поэтому пока не знаю куда тебе писать.

**Comment by dzmitry-varabei** [comment]
@ALisetskii Странно, похоже на баг. Так как ментор APP указан правильный
![image](https://user-images.githubusercontent.com/2429680/69966886-9404e000-1517-11ea-8bca-d9dd523be28d.png)
Если у тебя другая картинка - сабмитни плиз issue

**Comment by mikalai-sokarau** [comment]
Приветы, напиши мне плиз в телеграм - @MikalaiSokarau или в скайп - nklskr,
куда тебе удобнее :)

**Comment by ALisetskii** [comment]
@dzmitry-varabei 
в Stage Interview контакты предыдущего ментора
![image](https://user-images.githubusercontent.com/55103628/69994243-e02b4100-1566-11ea-8dbd-75f26d45bed2.png)

в Score
![image](https://user-images.githubusercontent.com/55103628/69994388-38624300-1567-11ea-89a8-42314fc49b1f.png)

ментор указан правильно но при нажатии:
![image](https://user-images.githubusercontent.com/55103628/69994435-516af400-1567-11ea-9bdc-ee53b57d92d1.png)

то же самое в профиле, поэтому пишу здесь что не вижу контактов, на случай если я слепой и вы мне укажите на кнопку которая была там все это время - спасибо за терпение.

**Comment by KotdenGit** [comment]
да я понял, вижу, со мной связался mikalai-sokarau,  я могу быть пока
прикреплённым к нему? если можно

вт, 3 дек. 2019 г. в 00:06, ALisetskii <notifications@github.com>:

**Comment by dzmitry-varabei** [comment]
@KotdenGit ты прикреплен

**Comment by dzmitry-varabei** [comment]
@ALisetskii подскажи, плиз, проблема осталась? Все ещё нет доступа к странице ментора?
Если так, ты поможешь, если оформишь баг тут (описание ситуации и скриншоты) - https://github.com/rolling-scopes/rsschool-app/issues. Скорее всего такая проблема не только у тебя

**Comment by JackFrost58** [comment]
Добрый вечер. Мой ментор написал, что больше не может проводить менторинг. Нужен новый ментор.

**Comment by vp090391** [comment]
Добрый вечер. Мне тоже нужен ментор. У того, что был мне назначен, нет времени, он об этом писал в соответствующем issue.

**Comment by dzmitry-varabei** [comment]
Если вы ищите ментора, напишите в https://github.com/rolling-scopes/rsschool-app/issues/239
