### ISSUE TITLE
Checkbox "Use Private Repositories" is not working

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes/rsschool-app#2487]
In the course settings for AWS Cloud Developer, May 2024 (https://app.rs.school/admin/courses), it is specified that students cannot use private repositories in RS School. However, I see that they have such an option available. This suggests that the checkbox "Use Private Repositories" is not functioning as expected.

Steps to Reproduce:

Go to the course settings for AWS Cloud Developer, May 2024.
Observe that the checkbox for "Use Private Repositories" is unchecked.
Check the list of repositories available for students [here](https://github.com/rolling-scopes-school/?q=awsdeveloper&type=all&language=&sort=).
Expected Result:
Students should not have access to private repositories if the "Use Private Repositories" checkbox is unchecked.

Actual Result:
Students have access to private repositories despite the "Use Private Repositories" checkbox being unchecked.

Screenshots:
![image](https://github.com/rolling-scopes/rsschool-app/assets/2429680/2f8d26ec-c6b4-41b0-9999-8185ba20e796)

**Comment by valerydluski** [comment]
@dzmitry-varabei
The checkbox works as intended; the issue was due to incorrect course configuration. In my opinion, there is no need to write additional logic for toggling the checkbox. Perhaps it would be better to create a warning when creating a course, emphasizing the need for careful setup. Attention should be paid to details such as private repositories and the minimum number of students per mentor. Problems have arisen more than once because of this.
