### ISSUE TITLE
https://rolling-scopes-school.github.io/AlekKar-JS2020Q3/calculator

### ISSUE THREAD

**Issue by AlekKar** [rolling-scopes/rsschool-app#538]
У меня запмерджины все такски.  А не одна не публикуется . Всё можно посмотреть исключительно у меня на странице. Дополнительный сайт не отвечает требованиям. Перетаскивай только шапку сайта, оставляя корни хозяину.

**Comment by apalchys** [comment]
@AlekKar 

1. Correct url is [https://rolling-scopes-school.github.io/**alekkar**-JS2020Q3/](https://rolling-scopes-school.github.io/alekkar-JS2020Q3/)
2. Your `gh-pages` branch is empty. https://github.com/rolling-scopes-school/alekkar-JS2020Q3/tree/gh-pages 
That's why you see 404. Please move content from your `webdev` branch to `gh-pages`.
